### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by killlowkey** [miaochenxi/chaoxing-sign-ui#10]
机型：苹果13
使用 safari 与 Alook 浏览器均出现如下情况，第一次使用时页面正常，之后页面都一片空白
![微信图片_20220420103651](https://user-images.githubusercontent.com/41176828/164135873-b71e97cf-f54b-447a-be72-589085df8767.jpg)

**Comment by cxOrz** [comment]
✅已修复

**Comment by killlowkey** [comment]
> ✅已修复

好的
