### ISSUE TITLE
“确认添加”点不动

### ISSUE THREAD

**Issue by 19819068211** [miaochenxi/chaoxing-sign-ui#11]
大佬，这个“确认添加”按钮点击之后没反应
![Uploading 屏幕截图(88).png…]()

**Comment by cxOrz** [comment]
可能接口没有运行，或者地址没有配置好

相关Issue：
https://github.com/miaochenxi/chaoxing-sign-ui/issues/2#issuecomment-1090456963

https://github.com/miaochenxi/chaoxing-sign-ui/issues/7#issue-1206083286
