### ISSUE TITLE
你好作者，我想请教一下身份过期和守护进程的问题

### ISSUE THREAD

**Issue by zrj866** [miaochenxi/chaoxing-sign-ui#12]
你好作者，尝试了几个账号，出现这个“身份过期，程序将关闭，请你使用手动填写用户名密码的方式登录！手动登录后身份信息刷新，之后可继续使用本地凭证！” 请问这个是什么原因呢？还有我在服务器用pm2守护了chaoxing-sign-cli API的进程，使其在ssh断开后保持正常工作，但是这样一来ui端只要ssh断开就不能访问了，请问ui端可以使用进程守护吗？

**Comment by cxOrz** [comment]
邮箱发下qq吧，说着方便些，看看为什么是过期

**Comment by xinchenmi** [comment]
好的，我的QQ是：2388013844
