### ISSUE TITLE
额，这个问题大吗，运行yarn install，安装到第三步的时候

### ISSUE THREAD

**Issue by moxiaowk** [miaochenxi/chaoxing-sign-ui#14]
warning "@emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @mui/icons-material@5.5.1" has incorrect peer dependency "react@^17.0.0".
warning " > @mui/material@5.5.3" has incorrect peer dependency "react@^17.0.0".
warning " > @mui/material@5.5.3" has incorrect peer dependency "react-dom@^17.0.0".
warning "@mui/material > @mui/base@5.0.0-alpha.74" has incorrect peer dependency "react@^17.0.0".
warning "@mui/material > @mui/base@5.0.0-alpha.74" has incorrect peer dependency "react-dom@^17.0.0".
warning "@mui/material > @mui/system@5.5.3" has incorrect peer dependency "react@^17.0.0".
warning "@mui/material > @mui/utils@5.5.3" has incorrect peer dependency "react@^17.0.0".
warning "@mui/material > @mui/system > @mui/private-theming@5.5.3" has incorrect peer dependency "react@^17.0.0".
warning "@mui/material > @mui/system > @mui/styled-engine@5.5.2" has incorrect peer dependency "react@^17.0.0".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > tailwindcss@3.0.23" has unmet peer dependency "autoprefixer@^10.0.2".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

**Comment by cxOrz** [comment]
问题不大，用的react18，mui那个版本要求的应该是17

**Comment by moxiaowk** [comment]
好的，感谢
