### ISSUE TITLE
ui界面能出个教程么

### ISSUE THREAD

**Issue by NANYUA** [miaochenxi/chaoxing-sign-ui#15]
跪求大佬出个ui的教程

**Comment by cxOrz** [comment]
1. 克隆一下代码
2. 项目目录中运行 `npm build`
3. 把生成的build文件夹里的东西，传到腾讯云开发里的静态网站托管。就能用默认提供的域名访问了
![image](https://user-images.githubusercontent.com/32982052/168593879-3e2051dc-e181-4030-a7e5-15c6a45f073d.png)

**Comment by cxOrz** [comment]
已添加更完整教程，见readme
