### ISSUE TITLE
静态网站部署与云函数接口搭配使用

### ISSUE THREAD

**Issue by Yancey597** [miaochenxi/chaoxing-sign-ui#16]

**Comment by Yancey597** [comment]
裂开了，不知道啥情况

**Comment by cxOrz** [comment]
是这样配置好的路径吗
![image](https://user-images.githubusercontent.com/32982052/171082724-ef4fb939-8d56-40da-ae42-abb031d9265c.png)

**Comment by cxOrz** [comment]
路由这样配置一下
![image](https://user-images.githubusercontent.com/32982052/171083330-ca70c23c-b240-44e5-8cdf-d270ad6b93ee.png)

**Comment by cxOrz** [comment]
接口地址看起来也怪怪的..
![image](https://user-images.githubusercontent.com/32982052/171083824-b87825d9-eb2b-478e-82a4-0745cf579f89.png)

**Comment by cxOrz** [comment]
http访问服务是这样，自己设一个路径，关联到云函数，就可以通过这个路径访问到
![image](https://user-images.githubusercontent.com/32982052/171084095-aff8ed90-28d2-4bea-bb14-7960071d4e5d.png)

**Comment by Yancey597** [comment]
> 接口地址看起来也怪怪的.. ![image](https://user-images.githubusercontent.com/32982052/171083824-b87825d9-eb2b-478e-82a4-0745cf579f89.png)
![image](https://user-images.githubusercontent.com/46004197/171084164-23cbda84-de88-4777-a4c3-10462c56e2de.png)

哦哦，这样有问题吗

**Comment by cxOrz** [comment]
应该是 baseUrl = 'https://chaoxingxuexi-............com'

这个baseUrl对应的是云函数的路径，不是这个静态网页地址

**Comment by Yancey597** [comment]
> 应该是 baseUrl = 'https://chaoxingxuexi-............com'
> 
> 这个baseUrl对应的是云函数的路径，不是这个静态网页地址
需要带触发路径吗
https://chaoxin*****1076.ap-shanghai.app.tcloudbase.com/chaoxing

**Comment by cxOrz** [comment]
要带出发路径的，能从这个地址成功访问到接口

**Comment by Yancey597** [comment]
> 要带出发路径的，能从这个地址成功访问到接口

感谢，成功解决，后续我还需要有维护操作吗

**Comment by cxOrz** [comment]
> > 要带出发路径的，能从这个地址成功访问到接口
> 
> 感谢，成功解决，后续我还需要有维护操作吗

仓库更新时，及时更新本地的代码就行

**Comment by Yancey597** [comment]
> > > 要带出发路径的，能从这个地址成功访问到接口
> > 
> > 
> > 感谢，成功解决，后续我还需要有维护操作吗
> 
> 仓库更新时，及时更新本地的代码就行

感谢，麻烦了
