### ISSUE TITLE
[Help] 本地yarn start可以运行，但部署到腾讯云托管无法添加账号

### ISSUE THREAD

**Issue by Last-ID** [miaochenxi/chaoxing-sign-ui#17]
cli运行在云服务器上，端口为默认，访问ip:5000可以看到“Welcome, chaoxing-sign-cli API service is running.”
![-](https://user-images.githubusercontent.com/44721512/173738264-d8c1c86a-e78a-4e32-949d-a7e581c93eb6.png)

本地通过yarn start启动ui后通过localhost:3000可以进行添加账户，签到操作，但是yarn build后部署到托管上无法添加账号，如 #11 
控制台输出如图
![--](https://user-images.githubusercontent.com/44721512/173738152-1885b357-28d2-4481-ad62-ea2a58516782.png)

**Comment by cxOrz** [comment]
错误报的应该挺清楚的，https访问的网页，不能进行http请求。应该保持一致。

**Comment by Last-ID** [comment]
ok，解决了，感谢
