### ISSUE TITLE
点击确认添加账号后404

### ISSUE THREAD

**Issue by kobeninya** [miaochenxi/chaoxing-sign-ui#18]
<img width="1097" alt="屏幕截图 2022-08-26 115355" src="https://user-images.githubusercontent.com/101168817/186814056-9bca0ce4-2e48-4705-9b7b-89d8cb77a232.png">

**Comment by cxOrz** [comment]
接口没部署好吧。

**Comment by kobeninya** [comment]
yarn dev 需要一直运行吗

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/186819444-d0063523-f356-40f6-b346-09b3e2e409ff.png)

`yarn dev` 是运行开发服务器，不应该在生产环境上使用。

可以构建一下，用 Nginx 来部署静态网站。

**Comment by kobeninya** [comment]
服务器上运行， seve.ts里面的api sever后面的地址需不需要改成ip：5000😭

**Comment by cxOrz** [comment]
src/config/api.js ：该文件中配置 baseUrl 变量为接口地址。改为 http://ip地址:5000

**Comment by kobeninya** [comment]
虽然按着做了，但但但..还是错了<img width="1115" alt="屏幕截图156" src="https://user-images.githubusercontent.com/101168817/186823594-38c74630-25ce-47c6-9877-1ffd6a938b32.png">

**Comment by kobeninya** [comment]
<img width="602" alt="屏幕截图 2022-08-26 125050" src="https://user-images.githubusercontent.com/101168817/186824527-5e22dc0f-9193-4e40-aaac-80f6e51035b5.png">

**Comment by cxOrz** [comment]
改的地方贴出来看看

**Comment by kobeninya** [comment]
我又重新全搞了一遍，还是报错，就改了这
<img width="389" alt="屏幕截图 2022-08-26 131430" src="https://user-images.githubusercontent.com/101168817/186829289-c6674bfb-c2d8-4976-84c4-b24b39e9a1ac.png">
里

**Comment by cxOrz** [comment]
接口那个仓库的代码，没改什么吧？那应该不会有问题啊。

防火墙开了没，有没有设置允许5000端口的TCP规则

**Comment by kobeninya** [comment]
<img width="866" alt="屏" src="https://user-images.githubusercontent.com/101168817/186829649-9d479218-1503-4fda-867d-1cd21a88adae.png">

**Comment by kobeninya** [comment]
<img width="626" alt="2-08-26 133651" src="https://user-images.githubusercontent.com/101168817/186829791-a065647e-e9ba-4cbb-8baf-dba09257dd85.png">

**Comment by kobeninya** [comment]
一点都没改，服务器是香港的，nginx是1.14.2

**Comment by cxOrz** [comment]
发下qq细说。加完记得删除消息。

**Comment by 1a2b3clong** [comment]
2730762155
