### ISSUE TITLE
构建时报错

### ISSUE THREAD

**Issue by moxiaowk** [miaochenxi/chaoxing-sign-ui#19]
[root@VM-16-15-centos chaoxing-sign-ui-main]# yarn build
yarn run v1.22.19
$ tsc && vite build
src/components/UserCard/UserCard.tsx:14:30 - error TS2307: Cannot find module '../../hooks/useLongPress' or its corresponding type declarations.

14 import { useLongPress } from '../../hooks/useLongPress'
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/UserCard/UserCard.tsx:26:31 - error TS7006: Parameter 'pos' implicitly has an 'any' type.

26   const [ref] = useLongPress((pos) => {
                                 ~~~


Found 2 errors in the same file, starting at: src/components/UserCard/UserCard.tsx:14

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cxOrz** [comment]
奇怪，我这边成功的
![image](https://user-images.githubusercontent.com/32982052/189162106-67509717-2f62-4b7a-a9df-a0ce92fbb9e1.png)

**Comment by moxiaowk** [comment]
我去，我的问题，文件放错位置了，解决了
