### ISSUE TITLE
ui版输入完账号密码后添加无反应

### ISSUE THREAD

**Issue by CLvax** [miaochenxi/chaoxing-sign-ui#2]
cli能正常签到，也添加了账号。但使用ui版点击确认提交无反应

**Comment by cxOrz** [comment]
> cli能正常签到，也添加了账号。但使用ui版点击确认提交无反应

是不是接口没运行，或者地址没有配置对

**Comment by Hetols** [comment]
外网访问需要将BaseAPI的localhost改为外网IP地址或域名

**Comment by cxOrz** [comment]
解决了就好⭐
