### ISSUE TITLE
点击未监听后始终处于加载中

### ISSUE THREAD

**Issue by S-Joan** [miaochenxi/chaoxing-sign-ui#20]
点击未监听后始终处于加载中
![6EYD RKZX3YLBD}04)WVMBH](https://user-images.githubusercontent.com/86223309/191575750-1b75636b-d9d7-458b-ae93-9e2c5104964f.png)
![$E%T1DS56USO0@M{X5V9FGU](https://user-images.githubusercontent.com/86223309/191575739-4b334c33-de91-45b5-81d9-6d14c26919f0.png)
并不会自动监测

**Comment by cxOrz** [comment]
![image](https://user-images.githubusercontent.com/32982052/191652907-046f2574-dccc-4a12-bdd3-a05a7407529d.png)

**Comment by cxOrz** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/issues/86

**Comment by S-Joan** [comment]
我这个构建指令npm run build  打出来提示这个正确嘛
![11](https://user-images.githubusercontent.com/86223309/191667895-08537954-d7b7-4eec-9206-b169e0142a2f.png)

**Comment by S-Joan** [comment]
感谢大佬已经解决了   pm2之前一直运行的chaoxing-sign-cli/server.ts  后来发现应该运行的是build目录下的server.js

**Comment by sxceocom** [comment]
另外问一下大佬   UI 仓库的项目能不能使用云盘的图片提交
