### ISSUE TITLE
部署后打开一片空白

### ISSUE THREAD

**Issue by xbn2002** [miaochenxi/chaoxing-sign-ui#22]
![2_L`EF$2G6}LBTCU63MIF V](https://user-images.githubusercontent.com/27143040/192310302-70b07fd9-9281-458e-a48b-b7d2191f7b75.png)
大佬，为什么部署以后打开一片空白，而且F12里竟然显示找不到那个css和js，我去看了下路径是对的啊？？
不管是远程访问还是服务器本地访问都不行，郁闷死了
![image](https://user-images.githubusercontent.com/27143040/192310726-96be2367-02df-4759-8a7a-748f3ee1bab9.png)

**Comment by xbn2002** [comment]
我感觉应该是baseUrl的问题，但无论怎么改都不行
我现在设置的是http://xxx.xxx.xx.xxx:5000
应该没问题吧
![image](https://user-images.githubusercontent.com/27143040/192317792-f6a3274f-0120-45b9-8cc4-50e505387585.png)

**Comment by UPman24** [comment]
不可能吧，你按照他的步骤打包就能看见效果了呀，所以你是一直本地打开使用的？

**Comment by xbn2002** [comment]
> 不可能吧，你按照他的步骤打包就能看见效果了呀，所以你是一直本地打开使用的？

之前是就用的cli，命令行用的。我查了下网上说法，react和vue之类的打包好像是会有这种情况，貌似是路由地址不对，但是我不会改

**Comment by xbn2002** [comment]
发现是路径的问题，必须放在根目录下才行
