### ISSUE TITLE
UI界面登陆卡片名字显示错误

### ISSUE THREAD

**Issue by zycn0910** [miaochenxi/chaoxing-sign-ui#25]
![捕获](https://user-images.githubusercontent.com/46790182/220693648-ce52f67e-e9a4-4757-bbf3-90e67aabca9e.PNG)

**Comment by cxOrz** [comment]
建议更新代码，再重新构建。

**Comment by beggerlove** [comment]
> 建议更新代码，再重新构建。
> 

博主  现在ui登录不上  点击添加没反应

**Comment by cxOrz** [comment]
> > 建议更新代码，再重新构建。
> 
> 博主 现在ui登录不上 点击添加没反应

刚试了一下，一切正常。
F12 看看请求是不是有什么问题，接口是不是没运行

**Comment by zycn0910** [comment]
> > 建议更新代码，再重新构建。
> 
> 博主 现在ui登录不上 点击添加没反应

全部删除之后，重新拉取仓库之后构建也是这个问题，名字显示错误

**Comment by cxOrz** [comment]
@zycn0910 另一个仓库的代码也更新了吗（接口）

**Comment by zycn0910** [comment]
> @zycn0910 另一个仓库的代码也更新了吗（接口）

更新之后名字显示正常，但是无法启动监听
如图
![QQ截图20230226163111](https://user-images.githubusercontent.com/46790182/221400366-f6da02f5-61eb-43f6-9d70-1f6a28679a22.png)
![QQ截图20230226163154](https://user-images.githubusercontent.com/46790182/221400368-67410b75-6259-4a83-8ec6-051a8e460c5f.png)

**Comment by cxOrz** [comment]
如图
![image](https://user-images.githubusercontent.com/32982052/221400444-ab71888d-d4b6-477e-abd5-24c2cc63c7d7.png)

**Comment by beggerlove** [comment]
博主  我注释parseEnc 这个函数启用腾讯云ocr后  还是识别失败  进ocr控制台看调用次数也没有被调用  这个enc貌似是被加密的  我室友用py解密了链接里面的enc  这是代码  
import re
import urllib
from flask import Flask

str = input('输入url: ')
url = urllib.parse.unquote(str)
for item in re.split('&', url):
    if item.startswith('enc'):
        print('\n' + '\n' + item[4:])

**Comment by cxOrz** [comment]
> 博主 我注释parseEnc 这个函数启用腾讯云ocr后 还是识别失败 进ocr控制台看调用次数也没有被调用 这个enc貌似是被加密的 我室友用py解密了链接里面的enc 这是代码 import re import urllib from flask import Flask
> 
> str = input('输入url: ') url = urllib.parse.unquote(str) for item in re.split('&', url): if item.startswith('enc'): print('\n' + '\n' + item[4:])

也是正常的
![image](https://user-images.githubusercontent.com/32982052/221482417-ae9255f8-dc3d-460f-ba8a-7897dc9852ca.png)
![image](https://user-images.githubusercontent.com/32982052/221482228-b7c367c0-f901-4fbd-882c-deaf4a859703.png)

**Comment by cxOrz** [comment]
务必确保chaoxing-sign-cli和chaoxing-sign-ui本地代码都是同步了最新的。
chaoxing-sign-cli 一定要先 build 才使最新的代码生效。

**Comment by cxOrz** [comment]
这几个小问题印象中都是去年出现的，老早就解决了的

**Comment by beggerlove** [comment]
> 
根据文档改了函数以及加了腾讯云的接口id和key  重新build了的cli项目   扫描二维码看着还是调用本地   并没有调用腾讯云    大佬带带   快折磨死了 哈哈哈
<img width="683" alt="image" src="https://user-images.githubusercontent.com/65286493/221596884-4ffeb323-76ad-4d08-8fba-4f3f691f0073.png">
![1677509669054](https://user-images.githubusercontent.com/65286493/221597276-ae081010-b0cf-4d93-8b69-a2cbc700e671.jpg)

**Comment by beggerlove** [comment]
根据文档改了函数以及加了腾讯云的接口id和key 重新build了的cli项目 扫描二维码看着还是调用本地 并没有调用腾讯云 大佬带带 快折磨死了 哈哈哈
<img width="502" alt="07c1e7c0e3ed82c4d694e6ccdb0a4fd" src="https://user-images.githubusercontent.com/65286493/221598153-9d0cec53-f89a-4952-a66e-4c7bb412eec6.png">
![image](https://user-images.githubusercontent.com/65286493/221598175-0342fc1c-4774-454e-93e4-2699b5859051.png)

**Comment by cxOrz** [comment]
显示是跨域问题，接口我加了允许任意域的响应头的。

是部署出问题了吧
