### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by Hetols** [miaochenxi/chaoxing-sign-ui#4]
在首页添加一个刷新按钮，按下后自动扫描所有已添加账号的签到状态和类型，并将其显示在首页的卡片上。
添加一个一键签到按钮，允许用户使用同一个参数对所有同签到类型的账号进行签到（列表选择），并将结果以列表的方式返回，运行前必须执行刷新指令。

**Comment by cxOrz** [comment]
不太好。

“自动扫描所有已添加账号的签到状态和类型”、“一键签到”：没有必要，而且会增加超星服务器的负担，自己的ip和账号也可能随时被ban，弹验证码。首页的用户卡片就是专门为了分开用户、分开使用，对全部用户的操作在绝大多数情况下是没有必要的，例如不一定两个用户就是一个班的人，扫它干嘛浪费资源，不如需要了再点他进去。

**Comment by Hetols** [comment]
> 不太好。
> 
> “自动扫描所有已添加账号的签到状态和类型”、“一键签到”：没有必要，而且会增加超星服务器的负担，自己的ip和账号也可能随时被ban，弹验证码。首页的用户卡片就是专门为了分开用户、分开使用，对全部用户的操作在绝大多数情况下是没有必要的，例如不一定两个用户就是一个班的人，扫它干嘛浪费资源，不如需要了再点他进去。

噢噢，确实是这样的，只是提议一下可以做出这样的功能
