### ISSUE TITLE
yarn start后报错

### ISSUE THREAD

**Issue by 9527-bit** [miaochenxi/chaoxing-sign-ui#5]
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.

**Comment by cxOrz** [comment]
“This probably means the system ran out of memory or someone called kill -9 on the process.”

**Comment by 9527-bit** [comment]
哦哦，应该是内存不够的原因了，🙇‍

**Comment by cxOrz** [comment]
在自己电脑上构建好，再上传服务器
