### ISSUE TITLE
添加账号失败

### ISSUE THREAD

**Issue by 9527-bit** [miaochenxi/chaoxing-sign-ui#6]
点击添加账户按钮没有反应

**Comment by 9527-bit** [comment]
在此项目 npm start 后有这个警告，是这里的原因吗 ？
WARNING in src/pages/DashBoard/DashBoard.js
  Line 303:6:  React Hook useEffect has a missing dependency: 'params.phone'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by cxOrz** [comment]
是不是没有运行接口

**Comment by 9527-bit** [comment]
[root@VM-20-13-centos chaoxing-sign-cli]# npm run serve

> chaoxing-sign-cli@2.2.2 serve
> node ./src/serve.js

API Server: http://localhost:5000
接口是运行状态的

**Comment by cxOrz** [comment]
f12看看控制台有什么错误没

**Comment by 9527-bit** [comment]
数据库打开成功
Start.js:20 disbaled
xhr.js:210 
        
      
        
        
      
        
      
       
        
       POST http://localhost:5000/login net::ERR_CONNECTION_REFUSED
dispatchXhrRequest @ xhr.js:210
xhrAdapter @ xhr.js:15
dispatchRequest @ dispatchRequest.js:58
request @ Axios.js:108
Axios.<computed> @ Axios.js:140
wrap @ bind.js:9
login @ Start.js:21
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4284
executeDispatch @ react-dom.development.js:9011
processDispatchQueueItemsInOrder @ react-dom.development.js:9043
processDispatchQueue @ react-dom.development.js:9056
dispatchEventsForPlugins @ react-dom.development.js:9067
(匿名) @ react-dom.development.js:9258
batchedUpdates$1 @ react-dom.development.js:25979
batchedUpdates @ react-dom.development.js:3984
dispatchEventForPluginEventSystem @ react-dom.development.js:9257
dispatchEvent @ react-dom.development.js:6435
dispatchDiscreteEvent @ react-dom.development.js:6410
createError.js:16 
        
       Uncaught (in promise) Error: Network Error
    at createError (createError.js:16:1)
    at XMLHttpRequest.handleError (xhr.js:117:1)

**Comment by 9527-bit** [comment]
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
Start.js:65 数据库打开成功
Start.js:20 disbaled
xhr.js:210 
        
      
        
        
      
        
      
       
        
       POST http://localhost:5000/login net::ERR_CONNECTION_REFUSED
dispatchXhrRequest @ xhr.js:210
xhrAdapter @ xhr.js:15
dispatchRequest @ dispatchRequest.js:58
request @ Axios.js:108
Axios.<computed> @ Axios.js:140
wrap @ bind.js:9
login @ Start.js:21
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4284
executeDispatch @ react-dom.development.js:9011
processDispatchQueueItemsInOrder @ react-dom.development.js:9043
processDispatchQueue @ react-dom.development.js:9056
dispatchEventsForPlugins @ react-dom.development.js:9067
(匿名) @ react-dom.development.js:9258
batchedUpdates$1 @ react-dom.development.js:25979
batchedUpdates @ react-dom.development.js:3984
dispatchEventForPluginEventSystem @ react-dom.development.js:9257
dispatchEvent @ react-dom.development.js:6435
dispatchDiscreteEvent @ react-dom.development.js:6410
createError.js:16 
        
       Uncaught (in promise) Error: Network Error
    at createError (createError.js:16:1)
    at XMLHttpRequest.handleError (xhr.js:117:1)
createError @ createError.js:16
handleError @ xhr.js:117
await in handleError(异步)
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4284
executeDispatch @ react-dom.development.js:9011
processDispatchQueueItemsInOrder @ react-dom.development.js:9043
processDispatchQueue @ react-dom.development.js:9056
dispatchEventsForPlugins @ react-dom.development.js:9067
(匿名) @ react-dom.development.js:9258
batchedUpdates$1 @ react-dom.development.js:25979
batchedUpdates @ react-dom.development.js:3984
dispatchEventForPluginEventSystem @ react-dom.development.js:9257
dispatchEvent @ react-dom.development.js:6435
dispatchDiscreteEvent @ react-dom.development.js:6410

**Comment by cxOrz** [comment]
应该还是接口问题
