### ISSUE TITLE
无法添加账号

### ISSUE THREAD

**Issue by 9527-bit** [miaochenxi/chaoxing-sign-ui#7]
两个项目对存放路径做要求的吗？并行或者是其他？

**Comment by 9527-bit** [comment]
![image](https://user-images.githubusercontent.com/63514538/163672240-3396a004-0ab9-49be-8954-11fa5eabb87f.png)
aip服务有在运行的

**Comment by miaochenxi** [comment]
给我的邮箱发一下qq或者其他联系方式吧。我加你看看啥情况

**Comment by cxOrz** [comment]
接口地址不对吧， 是不是写的localhost，应该写服务器地址

**Comment by 9527-bit** [comment]
我给你那个 未作任何修改的情况下，蒙蔽了 哈哈哈哈哈，谢谢你给我解答！！!



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miaochenxi/chaoxing-sign-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miaochenxi/chaoxing-sign-ui] 无法添加账号 (Issue #7)





 
接口地址不对吧， 是不是写的localhost，应该写服务器地址

**Comment by 9527-bit** [comment]
解决了

**Comment by 9527-bit** [comment]
确实，因该是这个问题没跑了&nbsp;

风萧萧兮易水寒，壮士打狗，一去不复还。 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月16日(星期六) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [miaochenxi/chaoxing-sign-ui] 无法添加账号 (Issue #7)





 
接口地址不对吧， 是不是写的localhost，应该写服务器地址

**Comment by 9527-bit** [comment]
QQ:2217180473
&nbsp;

风萧萧兮易水寒，壮士打狗，一去不复还。 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月16日(星期六) 晚上7:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [miaochenxi/chaoxing-sign-ui] 无法添加账号 (Issue #7)





 
给我的邮箱发一下qq或者其他联系方式吧。我加你看看啥情况
