### ISSUE TITLE
ui界面对服务器配置要求高吗

### ISSUE THREAD

**Issue by LeonardoNorskog** [miaochenxi/chaoxing-sign-ui#8]
这个ui界面所有的依赖安装之后70多mb，我本地可以运行起来，一到服务器就出现负载拉满cpu堵塞，这个对服务器要求高吗，我的是2h2g的，麻烦告诉一下

**Comment by cxOrz** [comment]
> 这个ui界面所有的依赖安装之后70多mb，我本地可以运行起来，一到服务器就出现负载拉满cpu堵塞，这个对服务器要求高吗，我的是2h2g的，麻烦告诉一下

要求不高，是不是在服务器运行npm start了，这样是启动开发服务器，不应该这样。应该在本地运行npm run build，把构建生成的静态网页，部署在Nginx或者用其他的你想用的

**Comment by LeonardoNorskog** [comment]
谢谢大佬，我弄好了呢

**Comment by LeonardoNorskog** [comment]
好像还是有问题呢，这个我属实不懂react，这个build之后会生成一个build文件夹，但是部署静态网站的时候只需要上传build文件夹里面的内容吗，还是说其他的所有的文件夹，包括src等的文件都需要上传呢，我总是出问题，部署之后可以打开界面，但是添加不了账号，我怀疑就是文件应该全部上传，但是上传之后也是打不开，php版本我选择的纯静态

**Comment by cxOrz** [comment]
> 好像还是有问题呢，这个我属实不懂react，这个build之后会生成一个build文件夹，但是部署静态网站的时候只需要上传build文件夹里面的内容吗，还是说其他的所有的文件夹，包括src等的文件都需要上传呢，我总是出问题，部署之后可以打开界面，但是添加不了账号，我怀疑就是文件应该全部上传，但是上传之后也是打不开，php版本我选择的纯静态

只需要上传build文件夹里的东西，如果用Nginx，就放在他的默认网页目录下

**Comment by cxOrz** [comment]
接口地址也应该改为服务器的IP+端口号
