### ISSUE TITLE
无法添加账号

### ISSUE THREAD

**Issue by LeonardoNorskog** [miaochenxi/chaoxing-sign-ui#9]
好像还是有问题呢，这个我属实不懂react，这个build之后会生成一个build文件夹，但是部署静态网站的时候只需要上传build文件夹里面的内容吗，还是说其他的所有的文件夹，包括src等的文件都需要上传呢，我总是出问题，部署之后可以打开界面，但是添加不了账号，我怀疑就是文件应该全部上传，但是上传之后也是打不开，php版本我选择的纯静态。如果只是上传build文件夹，那么接口要去哪里配置。

**Comment by cxOrz** [comment]
https://github.com/miaochenxi/chaoxing-sign-ui/issues/8#issuecomment-1100831181

**Comment by LeonardoNorskog** [comment]
![image](https://user-images.githubusercontent.com/78600910/163706909-78bc28ec-6fed-4a98-9fcd-b0dac023c6b0.png)
这是sh什么意思呢，我重新build了一次，之前也是遇到过，这个api.js是build之前改还是build之后改呢，我改了之后build就出现图片的情况

**Comment by cxOrz** [comment]
这个意思就是构建好了，build文件夹可以拿去部署了

**Comment by LeonardoNorskog** [comment]
只需要上传build文件夹就行是吧

**Comment by LeonardoNorskog** [comment]
好了好了，真不错。麻烦老哥了

**Comment by cxOrz** [comment]
🥹🥹🥹
